### ISSUE TITLE
some mods are visible to host but invisible for guests

### ISSUE THREAD

**Issue by iBoy386** [TDMP-Team/TDMP-Launcher-Public#10]
So my friend hosted a server, and some mods are just not visible to me, and whem I host the server it's invisible to my friend, and it's with almost all mods

**Comment by XCanG** [comment]
@iBoy386 Mods should have explicit support for TDMP. Look into descriptions in workshop to see if it supported. Some mods include it in title like `[TDMP]`

You could also search workshop with `TDMP` and then filter mods, this way you can find which mods support it.
